### ISSUE TITLE
Paryaya Seva with editable Seva Amount

### ISSUE THREAD

**Issue by bhargavibindhu** [PalimaruMatha/palimaruapp#9]
Paryaya Seva, I select any one of the sevas listed say Lakshadeepotsava Rs.125000/-
It takes me to the seva form to enter the Sevakarthru details. There is a provision to enter the Seva amount as well in this page. I believe this is not required, as the amount is fixed and decided by the mutt authorities.

**Comment by kirankaranam** [comment]
To help devotees who cannot afford to pay seva amounts for paryaya sea (some sea amounts are huge ~1250000/-) swamiji has decided to make it easy for them by enabling instalment payment scheme. In this scheme, devotee can book any paryaya seva by paying the amounts in instalments periodically according to his convenience. Hence, the seva amount is editable. in the sense, user can pay 10,000 as first instalment and from there on keep making small payments as and when he wants.
